/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPagination: typeof import('vant/es')['Pagination']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSkeletonImage: typeof import('vant/es')['SkeletonImage']
    VanSkeletonParagraph: typeof import('vant/es')['SkeletonParagraph']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSticky: typeof import('vant/es')['Sticky']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    VanText: typeof import('vant/es')['Text']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
    VanTreeSelect: typeof import('vant/es')['TreeSelect']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
